// <auto-generated />
using System;
using HealthCampus.Services.AppFileAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HealthCampus.Services.AppFileAPI.Migrations
{
    [DbContext(typeof(AppFileDbContext))]
    [Migration("20230803155642_initialcreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HealthCampus.Services.AppFileAPI.Models.AppFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BlobContainer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("ContentTypeId")
                        .HasColumnType("tinyint");

                    b.Property<string>("DownloadUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Duration")
                        .HasColumnType("int");

                    b.Property<bool?>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifiedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OriginalName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UploadedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UploadedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ContentTypeId");

                    b.ToTable("AppFiles");
                });

            modelBuilder.Entity("HealthCampus.Services.AppFileAPI.Models.FileContentType", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnType("tinyint");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FileContentTypes");

                    b.HasData(
                        new
                        {
                            Id = (byte)11,
                            Description = "Joint Photographic Experts Group",
                            Extension = ".jpg",
                            MediaType = "image",
                            SubType = "jpeg"
                        },
                        new
                        {
                            Id = (byte)12,
                            Description = "Joint Photographic Experts Group",
                            Extension = ".jpeg",
                            MediaType = "image",
                            SubType = "jpeg"
                        },
                        new
                        {
                            Id = (byte)13,
                            Description = "Graphics Interchange Format",
                            Extension = ".gif",
                            MediaType = "image",
                            SubType = "gif"
                        },
                        new
                        {
                            Id = (byte)14,
                            Description = "Windows Bitmap",
                            Extension = ".bmp",
                            MediaType = "image",
                            SubType = "bmp"
                        },
                        new
                        {
                            Id = (byte)15,
                            Description = "Tagged Image File Format",
                            Extension = ".tiff",
                            MediaType = "image",
                            SubType = "tiff"
                        },
                        new
                        {
                            Id = (byte)16,
                            Description = "WebP image format",
                            Extension = ".webp",
                            MediaType = "image",
                            SubType = "webp"
                        },
                        new
                        {
                            Id = (byte)17,
                            Description = "Scalable Vector Graphics",
                            Extension = ".svg",
                            MediaType = "image",
                            SubType = "svg+xml"
                        },
                        new
                        {
                            Id = (byte)18,
                            Description = "Windows Icon file format",
                            Extension = ".ico",
                            MediaType = "image",
                            SubType = "x-icon"
                        },
                        new
                        {
                            Id = (byte)19,
                            Description = "Animated Portable Network Graphics",
                            Extension = ".apng",
                            MediaType = "image",
                            SubType = "apng"
                        },
                        new
                        {
                            Id = (byte)20,
                            Description = "AV1 Image File Format",
                            Extension = ".avif",
                            MediaType = "image",
                            SubType = "avif"
                        },
                        new
                        {
                            Id = (byte)21,
                            Description = "High Efficiency Image Format (.HEIC/.HEIF)",
                            Extension = ".heif",
                            MediaType = "image",
                            SubType = "heif"
                        },
                        new
                        {
                            Id = (byte)22,
                            Description = "High Efficiency Image Format (.HEIC/.HEIF)",
                            Extension = ".heic",
                            MediaType = "image",
                            SubType = "heic"
                        },
                        new
                        {
                            Id = (byte)23,
                            Description = "Portable Network Graphics",
                            Extension = ".png",
                            MediaType = "image",
                            SubType = "png"
                        },
                        new
                        {
                            Id = (byte)31,
                            Description = "Microsoft Word",
                            Extension = ".doc",
                            MediaType = "application",
                            SubType = "msword"
                        },
                        new
                        {
                            Id = (byte)32,
                            Description = "Microsoft Word Open XML document",
                            Extension = ".docx",
                            MediaType = "application",
                            SubType = "vnd.openxmlformats-officedocument.wordprocessingml.document"
                        },
                        new
                        {
                            Id = (byte)33,
                            Description = "Microsoft Excel Binary File Format",
                            Extension = ".xls",
                            MediaType = "application",
                            SubType = "vnd.ms-excel"
                        },
                        new
                        {
                            Id = (byte)34,
                            Description = "Microsoft Excel Open XML spreadsheet",
                            Extension = ".xlsx",
                            MediaType = "application",
                            SubType = "vnd.openxmlformats-officedocument.spreadsheetml.sheet"
                        },
                        new
                        {
                            Id = (byte)35,
                            Description = "Microsoft PowerPoint",
                            Extension = ".ppt",
                            MediaType = "application",
                            SubType = "vnd.ms-powerpoint"
                        },
                        new
                        {
                            Id = (byte)36,
                            Description = "PowerPoint Open XML presentation",
                            Extension = ".pptx",
                            MediaType = "application",
                            SubType = "vnd.openxmlformats-officedocument.presentationml.presentation"
                        },
                        new
                        {
                            Id = (byte)37,
                            Description = "Portable Document Format",
                            Extension = ".pdf",
                            MediaType = "application",
                            SubType = "pdf"
                        },
                        new
                        {
                            Id = (byte)38,
                            Description = "Rich Text Format",
                            Extension = ".rtf",
                            MediaType = "application",
                            SubType = "rtf"
                        },
                        new
                        {
                            Id = (byte)39,
                            Description = "Compressed ZIP Archive",
                            Extension = ".zip",
                            MediaType = "application",
                            SubType = "zip"
                        },
                        new
                        {
                            Id = (byte)40,
                            Description = "RAR Archive",
                            Extension = ".rar",
                            MediaType = "application",
                            SubType = "x-rar-compressed"
                        },
                        new
                        {
                            Id = (byte)41,
                            Description = "7-Zip Archive",
                            Extension = ".7z",
                            MediaType = "application",
                            SubType = "x-7z-compressed"
                        },
                        new
                        {
                            Id = (byte)51,
                            Description = "Audio Video Interleave",
                            Extension = ".avi",
                            MediaType = "video",
                            SubType = "avi"
                        },
                        new
                        {
                            Id = (byte)52,
                            Description = "Flash Video",
                            Extension = ".flv",
                            MediaType = "video",
                            SubType = "x-flv"
                        },
                        new
                        {
                            Id = (byte)53,
                            Description = "Windows Media Video",
                            Extension = ".wmv",
                            MediaType = "video",
                            SubType = "x-ms-wmv"
                        },
                        new
                        {
                            Id = (byte)54,
                            Description = "QuickTime",
                            Extension = ".mov",
                            MediaType = "video",
                            SubType = "quicktime"
                        },
                        new
                        {
                            Id = (byte)55,
                            Description = "MPEG",
                            Extension = ".mp4",
                            MediaType = "video",
                            SubType = "mp4"
                        },
                        new
                        {
                            Id = (byte)56,
                            Description = "Ogg",
                            Extension = ".ogg",
                            MediaType = "video",
                            SubType = "ogg"
                        },
                        new
                        {
                            Id = (byte)57,
                            Description = "MPEG-4 Part 14 video file format",
                            Extension = ".m4v",
                            MediaType = "video",
                            SubType = "x-m4v"
                        },
                        new
                        {
                            Id = (byte)58,
                            Description = "Matroska Multimedia Container",
                            Extension = ".mkv",
                            MediaType = "video",
                            SubType = "x-matroska"
                        },
                        new
                        {
                            Id = (byte)61,
                            Description = "MPEG-1 or MPEG-2 Audio Layer III",
                            Extension = ".mp3",
                            MediaType = "audio",
                            SubType = "mpeg"
                        },
                        new
                        {
                            Id = (byte)62,
                            Description = "Waveform Audio File Format",
                            Extension = ".wav",
                            MediaType = "audio",
                            SubType = "wav"
                        },
                        new
                        {
                            Id = (byte)63,
                            Description = "Windows Media Audio",
                            Extension = ".wma",
                            MediaType = "audio",
                            SubType = "x-ms-wma"
                        },
                        new
                        {
                            Id = (byte)64,
                            Description = "Advanced Audio Codec",
                            Extension = ".aac",
                            MediaType = "audio",
                            SubType = "aac"
                        },
                        new
                        {
                            Id = (byte)65,
                            Description = "Audio Interchange File Format",
                            Extension = ".aiff",
                            MediaType = "audio",
                            SubType = "aiff"
                        },
                        new
                        {
                            Id = (byte)71,
                            Description = "Comma-Separated Values",
                            Extension = ".csv",
                            MediaType = "text",
                            SubType = "csv"
                        },
                        new
                        {
                            Id = (byte)72,
                            Description = "Plain text",
                            Extension = ".txt",
                            MediaType = "text",
                            SubType = "plain"
                        },
                        new
                        {
                            Id = (byte)73,
                            Description = "HyperText Markup Language",
                            Extension = ".html",
                            MediaType = "text",
                            SubType = "html"
                        });
                });

            modelBuilder.Entity("HealthCampus.Services.AppFileAPI.Models.AppFile", b =>
                {
                    b.HasOne("HealthCampus.Services.AppFileAPI.Models.FileContentType", "ContentType")
                        .WithMany()
                        .HasForeignKey("ContentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContentType");
                });
#pragma warning restore 612, 618
        }
    }
}
